In [51]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [52]:
from sklearn.datasets import make_classification

In [53]:
## Create dataset
X,y = make_classification(n_samples=1000,n_features=10,n_classes=2,random_state=10)

In [54]:
X = pd.DataFrame(X)

In [55]:
X.head(4)

0         1         2         3         4         5         6  \
0 -1.005838 -0.376539 -0.620180 -0.157567 -1.120805 -0.589091 -1.574578   
1  0.411180  0.762409 -0.784210 -0.096479 -0.408758 -0.665780  0.210942   
2 -1.525408  2.227934  0.547727 -0.341481 -0.817577  0.423091 -2.663678   
3 -1.374563  0.061129 -0.995868 -0.214351 -0.558957  0.064870 -2.149167   

          7         8         9  
0  1.678046  1.080180  0.353587  
1 -0.850449 -0.461301  1.062237  
2  2.440042  1.698919 -0.705302  
3  2.294192 -1.383965  0.806924

In [56]:
from sklearn.model_selection import train_test_split
X_train , X_test ,y_train , y_test = train_test_split(X,y,test_size=0.30,random_state=42)

In [57]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression()
log_reg.fit(X_train,y_train)

LogisticRegression()

In [58]:
y_pred = log_reg.predict(X_test)

In [59]:
y_pred

array([1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1])

In [60]:
## Probability that a test data belongs to cat1 , cat2
log_reg.predict_proba(X_test)

array([[1.40764087e-01, 8.59235913e-01],
       [2.54888745e-01, 7.45111255e-01],
       [7.52400720e-01, 2.47599280e-01],
       [3.51805502e-02, 9.64819450e-01],
       [2.94986282e-01, 7.05013718e-01],
       [4.69223355e-01, 5.30776645e-01],
       [5.00831276e-02, 9.49916872e-01],
       [9.72196839e-01, 2.78031611e-02],
       [9.81606729e-01, 1.83932711e-02],
       [1.02194954e-01, 8.97805046e-01],
       [8.95308138e-01, 1.04691862e-01],
       [8.17986278e-01, 1.82013722e-01],
       [5.79266445e-02, 9.42073355e-01],
       [5.78096928e-01, 4.21903072e-01],
       [8.87451928e-01, 1.12548072e-01],
       [3.02041020e-02, 9.69795898e-01],
       [3.24714431e-01, 6.75285569e-01],
       [1.88330045e-01, 8.11669955e-01],
       [5.82671089e-01, 4.17328911e-01],
       [4.98166288e-01, 5.01833712e-01],
       [2.43092922e-01, 7.56907078e-01],
       [9.22650005e-01, 7.73499952e-02],
       [7.47696069e-01, 2.52303931e-01],
       [4.49108024e-02, 9.55089198e-01],
       [8.834093

In [61]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [62]:
accuracy_score(y_test,y_pred)

0.8866666666666667

In [63]:
confusion_matrix(y_test,y_pred)

array([[126,  22],
       [ 12, 140]])

In [64]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.91      0.85      0.88       148
           1       0.86      0.92      0.89       152

    accuracy                           0.89       300
   macro avg       0.89      0.89      0.89       300
weighted avg       0.89      0.89      0.89       300



### Hyperparameter tuning and cross validation

In [65]:
model = LogisticRegression()
penalty  = ['l1','l2','elasticnet']
c_values = [100,10,1.0,0.1,0.01]
solvers = ['newton-cg','lbfgs','sag','saga','liblinear']

In [66]:
params = dict(penalty = penalty,C = c_values,solver = solvers)

In [67]:
from sklearn.model_selection import StratifiedKFold
cv = StratifiedKFold(5)

In [68]:
## GridSearchCV
from sklearn.model_selection import GridSearchCV

grid = GridSearchCV(estimator=model,param_grid=params,scoring='accuracy',cv=cv,n_jobs=-1)

In [69]:
print(grid)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'sag', 'saga',
                                    'liblinear']},
             scoring='accuracy')


In [70]:
grid.fit(X_train,y_train)

c:\Users\hanni\Desktop\NOTES\Semester 5\ML\ml_env\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning: 
200 fits failed out of a total of 375.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\hanni\Desktop\NOTES\Semester 5\ML\ml_env\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\hanni\Desktop\NOTES\Semester 5\ML\ml_env\Lib\site-packages\sklearn\base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\hanni\Desktop\NOTES\Semes

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'sag', 'saga',
                                    'liblinear']},
             scoring='accuracy')

In [71]:
grid.best_params_

{'C': 0.1, 'penalty': 'l1', 'solver': 'saga'}

In [72]:
grid.best_score_

np.float64(0.8571428571428571)

In [74]:
y_p = grid.predict(X_test)

## Randomised Search CV

In [75]:
from sklearn.model_selection import RandomizedSearchCV


In [76]:
randomcv = RandomizedSearchCV(estimator=model,param_distributions=params,cv = 5,scoring='accuracy')

In [77]:
randomcv.fit(X_train,y_train)

c:\Users\hanni\Desktop\NOTES\Semester 5\ML\ml_env\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning: 
25 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\hanni\Desktop\NOTES\Semester 5\ML\ml_env\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\hanni\Desktop\NOTES\Semester 5\ML\ml_env\Lib\site-packages\sklearn\base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\hanni\Desktop\NOTES\Semester

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1.0, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['newton-cg', 'lbfgs', 'sag',
                                                   'saga', 'liblinear']},
                   scoring='accuracy')

In [78]:
randomcv.best_score_

np.float64(0.8571428571428571)

In [79]:
randomcv.best_params_

{'solver': 'saga', 'penalty': 'l1', 'C': 0.1}